import { type Vino } from "./types"

/**
 * Catálogo de demostración. Datos inventados para maquetar la tienda —
 * ningún vino, bodega ni precio de acá es real.
 *
 * Al conectar Supabase, este archivo se borra y solo cambia el cuerpo de
 * `queries.ts`; los componentes no se enteran.
 */
export const VINOS_MOCK: readonly Vino[] = [
  {
    id: "1",
    slug: "malbec-reserva",
    imagen: "/producto-vinedo-real.png",
    imagenCaja: "/caja-vinedo-real.png",
    nombre: "Reserva",
    varietal: "Malbec",
    tipo: "tinto",
    bodega: "Viñedo Real",
    anio: 2021,
    precio: 18900,
    precioAnterior: 23900,
    notas: "Ciruela madura, violetas y un fondo de vainilla del roble.",
    maridaje: "Carnes rojas, cordero al horno, quesos estacionados.",
    graduacion: "14,2%",
    destacado: true,
    masVendido: true,
  },
  {
    id: "2",
    slug: "cabernet-franc-altura",
    imagen: "/producto-valle-profundo.png",
    imagenCaja: "/caja-valle-profundo.png",
    nombre: "Altura",
    varietal: "Cabernet Franc",
    tipo: "tinto",
    bodega: "Viñedo Real",
    anio: 2020,
    precio: 24500,
    notas: "Pimiento asado, frutos negros y taninos firmes.",
    maridaje: "Bife de chorizo, guisos, quesos duros.",
    graduacion: "13,8%",
    destacado: true,
    masVendido: true,
  },
  {
    id: "3",
    slug: "chardonnay-barrica",
    imagen: "/producto-brisa-marina.png",
    imagenCaja: "/caja-brisa-marina.png",
    nombre: "Barrica",
    varietal: "Chardonnay",
    tipo: "blanco",
    bodega: "Brisa Marina",
    anio: 2022,
    precio: 15400,
    precioAnterior: 19200,
    notas: "Durazno blanco, manteca y un dejo de avellana.",
    maridaje: "Pastas con crema, pollo al limón, pescados grasos.",
    graduacion: "13,5%",
    destacado: false,
    masVendido: true,
  },
  {
    id: "4",
    slug: "sauvignon-blanc-fresco",
    imagen: "/producto-brisa-marina.png",
    imagenCaja: "/caja-brisa-marina.png",
    nombre: "Fresco",
    varietal: "Sauvignon Blanc",
    tipo: "blanco",
    bodega: "Finca La Ladera",
    anio: 2023,
    precio: 12800,
    notas: "Pomelo, hierba recién cortada y acidez vibrante.",
    maridaje: "Mariscos, ceviche, ensaladas verdes.",
    graduacion: "12,9%",
    destacado: false,
    masVendido: true,
  },
  {
    id: "5",
    slug: "rosado-de-malbec",
    imagen: "/producto-flor-de-seda.png",
    imagenCaja: "/caja-flor-de-seda.png",
    nombre: "Sutil",
    varietal: "Malbec Rosé",
    tipo: "rosado",
    bodega: "Flor de Seda",
    anio: 2023,
    precio: 11900,
    notas: "Frutilla, pomelo rosado y final seco.",
    maridaje: "Picadas, sushi, comida asiática.",
    graduacion: "12,5%",
    destacado: true,
    masVendido: true,
  },
  {
    id: "6",
    slug: "espumante-brut-nature",
    imagen: "/producto-celebracion.png",
    imagenCaja: "/caja-celebracion.png",
    nombre: "Festivo",
    varietal: "Brut Nature",
    tipo: "espumante",
    bodega: "Casa Celebración",
    anio: 2022,
    precio: 21500,
    precioAnterior: 26000,
    notas: "Burbuja fina, manzana verde y notas de panadería.",
    maridaje: "Aperitivo, ostras, frituras.",
    graduacion: "12,0%",
    destacado: true,
    masVendido: true,
  },
  {
    id: "7",
    slug: "pinot-noir-ladera",
    imagen: "/producto-valle-profundo.png",
    imagenCaja: "/caja-valle-profundo.png",
    nombre: "Ladera",
    varietal: "Pinot Noir",
    tipo: "tinto",
    bodega: "Finca La Ladera",
    anio: 2021,
    precio: 27800,
    notas: "Cereza, tierra húmeda y taninos sedosos.",
    maridaje: "Salmón, risotto de hongos, jamón crudo.",
    graduacion: "13,2%",
    destacado: true,
    masVendido: true,
  },
  {
    id: "8",
    slug: "blend-de-corte",
    imagen: "/producto-valle-profundo.png",
    imagenCaja: "/caja-valle-profundo.png",
    nombre: "Gran Corte",
    varietal: "Malbec · Cabernet · Petit Verdot",
    tipo: "tinto",
    bodega: "Viñedo Real",
    anio: 2019,
    precio: 42000,
    notas: "Complejo y largo: fruta negra, tabaco y chocolate amargo.",
    maridaje: "Cortes de guarda, caza, quesos azules.",
    graduacion: "14,5%",
    destacado: true,
    masVendido: true,
  },
  {
    id: "9",
    slug: "torrontes-de-altura",
    imagen: "/producto-brisa-marina.png",
    imagenCaja: "/caja-brisa-marina.png",
    nombre: "Aromático",
    varietal: "Torrontés",
    tipo: "blanco",
    bodega: "Flor de Seda",
    anio: 2023,
    precio: 10900,
    precioAnterior: 13500,
    notas: "Jazmín, damasco y final fresco.",
    maridaje: "Empanadas, comida especiada, quesos frescos.",
    graduacion: "12,8%",
    destacado: false,
    masVendido: false,
  },
  {
    id: "10",
    slug: "syrah-nocturno",
    imagen: "/producto-vinedo-real.png",
    imagenCaja: "/caja-vinedo-real.png",
    nombre: "Nocturno",
    varietal: "Syrah",
    tipo: "tinto",
    bodega: "Bodega del Valle",
    anio: 2020,
    precio: 19800,
    notas: "Pimienta negra, mora y un ahumado sutil.",
    maridaje: "Asado, embutidos, guisos de invierno.",
    graduacion: "14,0%",
    destacado: false,
    masVendido: false,
  },
  {
    id: "11",
    slug: "rosado-pinot",
    imagen: "/producto-flor-de-seda.png",
    imagenCaja: "/caja-flor-de-seda.png",
    nombre: "Amanecer",
    varietal: "Pinot Noir Rosé",
    tipo: "rosado",
    bodega: "Flor de Seda",
    anio: 2023,
    precio: 13400,
    precioAnterior: 16800,
    notas: "Frambuesa, cítricos y textura ligera.",
    maridaje: "Ensaladas, pescados, tartas saladas.",
    graduacion: "12,3%",
    destacado: false,
    masVendido: false,
  },
  {
    id: "12",
    slug: "espumante-rose",
    imagen: "/producto-celebracion.png",
    imagenCaja: "/caja-celebracion.png",
    nombre: "Celebración",
    varietal: "Extra Brut Rosé",
    tipo: "espumante",
    bodega: "Casa Celebración",
    anio: 2022,
    precio: 23900,
    notas: "Frutos rojos, burbuja persistente y final seco.",
    maridaje: "Postres poco dulces, aperitivos, sushi.",
    graduacion: "12,2%",
    destacado: true,
    masVendido: false,
  },
  {
    id: "13",
    slug: "merlot-suave",
    imagen: "/producto-vinedo-real.png",
    imagenCaja: "/caja-vinedo-real.png",
    nombre: "Suave",
    varietal: "Merlot",
    tipo: "tinto",
    bodega: "Bodega del Valle",
    anio: 2022,
    precio: 14200,
    notas: "Ciruela, taninos redondos y final amable.",
    maridaje: "Pastas con salsa roja, pizzas, milanesas.",
    graduacion: "13,4%",
    destacado: false,
    masVendido: false,
  },
  {
    id: "14",
    slug: "viognier-blanco",
    imagen: "/producto-brisa-marina.png",
    imagenCaja: "/caja-brisa-marina.png",
    nombre: "Sereno",
    varietal: "Viognier",
    tipo: "blanco",
    bodega: "Brisa Marina",
    anio: 2023,
    precio: 16700,
    notas: "Durazno, flores blancas y cuerpo untuoso.",
    maridaje: "Cerdo, curries suaves, quesos cremosos.",
    graduacion: "13,6%",
    destacado: false,
    masVendido: false,
  },
  {
    id: "15",
    slug: "bonarda-de-parral",
    imagen: "/producto-vinedo-real.png",
    imagenCaja: "/caja-vinedo-real.png",
    nombre: "Parral",
    varietal: "Bonarda",
    tipo: "tinto",
    bodega: "Bodega del Valle",
    anio: 2021,
    precio: 13900,
    precioAnterior: 17500,
    notas: "Fruta roja jugosa, poca madera y mucha bebilidad.",
    maridaje: "Picadas, empanadas, pastas simples.",
    graduacion: "13,1%",
    destacado: false,
    masVendido: false,
  },
  {
    id: "16",
    slug: "espumante-dulce",
    imagen: "/producto-celebracion.png",
    imagenCaja: "/caja-celebracion.png",
    nombre: "Dulce Tarde",
    varietal: "Demi-Sec",
    tipo: "espumante",
    bodega: "Casa Celebración",
    anio: 2023,
    precio: 12500,
    notas: "Manzana, miel suave y burbuja cremosa.",
    maridaje: "Postres, frutas, pastelería.",
    graduacion: "11,8%",
    destacado: false,
    masVendido: false,
  },
] as const
